# Site settings
title: IMPACT Consortium |
description: Immune & Microbiota Monitoring
baseurl: ""      # leave blank unless in a subfolder
url: "https://impactkidshealth.github.io"

# Theme
theme: beautiful-jekyll

# Logo (appears top left)
logo: /assets/images/IMPACT%20logo%202026.png

# Navigation menu
navigation:
  - title: IMPACT
    url: /impact/
  - title: Collaborations
    url: /collaborations/
  - title: Projects
    url: /projects/
  - title: Output
    url: /output/
  - title: News
    url: /news/

# Hero / homepage background
hero_image: /assets/images/hero-background.jpg  # your main homepage background

# Custom CSS (for extra styling if needed)
custom_css: /assets/css/custom.css
